### ISSUE TITLE
How to get tweets with other user/key word?

### ISSUE THREAD

**Issue by conglyne222** [duyhung2201/Distributed_Computing_20192#1]
Dạ chào anh, em đang implement theo script của anh nhưng tài khoản của Donald Trump đã bị suspended thì anh cho em hỏi là query_url mình lấy ntn để lấy của người khác. Chẳng hạn là Elon Musk...

**Comment by hungldorai** [comment]
> 

Chào em, em có thể thay twitter_id ở phần query_data nhé. Vào thời điểm đó twitter id của tài khoản @RealDonaldTrump là 25073877. Nếu em muốn lấy của Elon Musk thì có thể thay twitter_id bằng 44196397.

**Comment by duyhung2201** [comment]
> Dạ chào anh, em đang implement theo script của anh nhưng tài khoản của Donald Trump đã bị suspended thì anh cho em hỏi là query_url mình lấy ntn để lấy của người khác. Chẳng hạn là Elon Musk...

Chào em, em có thể thay twitter_id ở phần query_data nhé. Vào thời điểm đó twitter id của tài khoản @RealDonaldTrump là 25073877. Nếu em muốn lấy của Elon Musk thì có thể thay twitter_id bằng 44196397.

**Comment by conglyne222** [comment]
Dạ em cảm ơn anh ạ. Anh cho em hỏi sau khi mình có tweet rồi thì dùng model nào để predict sentiment (positive/negative) cho tweet text ạ?
